"use client";

import React from "react";
import { CropSelector } from "@/components/dashboard/farmrisk/CropSelector";
import { LocationSearchBar } from "@/components/dashboard/overview/LocationSearchBar";
import { useLanguage } from "@/hooks/useLanguage";
import { useSelectedCrop } from "@/hooks/useSelectedCrop";
import { Sprout } from "lucide-react";
import SowingTimeline from "./presowing/SowingTimeline";
import SeedSelection from "./presowing/SeedSelection";
import FieldPreparation from "./presowing/FieldPreparation";
import FertilizerPlan from "./presowing/FertilizerPlan";
import IrrigationSchedule from "./presowing/IrrigationSchedule";
import WeedManagement from "./presowing/WeedManagement";
import PestDiseaseCalendar from "./presowing/PestDiseaseCalendar";

/**
 * "Pre-Sowing" Tool Page
 * Features 7 structured agronomic decision-support widgets:
 * 1. Sowing window / timeline
 * 2. Seed selection
 * 3. Field preparation
 * 4. Fertilizer plan
 * 5. Irrigation schedule
 * 6. Weed management
 * 7. Pest & disease calendar
 *
 * Designed to render markdown generated by RAG/AI models.
 * Kept empty by default with skeleton loading and error states.
 */
export function PreSowing() {
  const { t } = useLanguage();
  const { selectedCrop } = useSelectedCrop();

  const title = t.tools?.preSowing || "Pre-Sowing";
  const desc =
    t.tools?.preSowingDesc ||
    "Agronomic planning, sowing guidelines, and land preparation advisory before planting.";

  return (
    <div className="flex flex-col gap-4 w-full">
      {/* CROP & LOCATION SELECTORS */}
      <CropSelector />
      <LocationSearchBar />

      {/* PAGE INTRO BANNER */}
      <div className="w-full bg-gradient-to-r from-emerald-500/10 via-emerald-500/5 to-transparent border border-emerald-500/20 rounded-xl p-4 sm:p-5 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-emerald-500 text-white shadow-sm">
            <Sprout className="size-5" />
          </div>
          <div>
            <h2 className="text-base sm:text-lg font-bold text-foreground">
              {title}
            </h2>
            <p className="text-xs text-muted-foreground leading-relaxed">
              {desc}
            </p>
          </div>
        </div>
        <div className="hidden sm:flex items-center px-3 py-1 rounded-full bg-background/80 border border-border text-xs font-semibold text-emerald-600 dark:text-emerald-400 shrink-0">
          {selectedCrop.name}
        </div>
      </div>

      {/* 7 PRE-SOWING COMPONENTS GRID */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 w-full items-stretch">
        {/* ROW 1: Sowing Window / Timeline + Seed Selection */}
        <div className="col-span-1 flex">
          <SowingTimeline />
        </div>
        <div className="col-span-1 flex">
          <SeedSelection />
        </div>

        {/* ROW 2: Field Preparation + Fertilizer Plan */}
        <div className="col-span-1 flex">
          <FieldPreparation />
        </div>
        <div className="col-span-1 flex">
          <FertilizerPlan />
        </div>

        {/* ROW 3: Irrigation Schedule + Weed Management */}
        <div className="col-span-1 flex">
          <IrrigationSchedule />
        </div>
        <div className="col-span-1 flex">
          <WeedManagement />
        </div>

        {/* ROW 4: Pest & Disease Calendar (Full width on large screens) */}
        <div className="col-span-1 lg:col-span-2 flex">
          <PestDiseaseCalendar />
        </div>
      </div>
    </div>
  );
}

export default PreSowing;
